version: "3.3"
   
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myuser 
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
  api:
    container_name: api
    build:
        context: api/
        dockerfile: Dockerfile
    command: sh -c "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  client:
    container_name: client
    build:
        context: client/
        dockerfile: Dockerfile
    command: sh -c "yarn && quasar dev"
    volumes:
    - ./client:/usr/src/app
    - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on: 
      - api

volumes:
    postgres_data: