# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Client CI

on:
  push:
    paths:
      - client/**
  pull_request:
    paths:
      - client/**

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build db and api containers
      run: docker-compose up -d --build client
    
    - name: Run tests
      run: docker-compose run client quasar test --unit jest

    - name: Run stylesheet analysis
      run: docker-compose run client yarn lint
